---
# prerequisite variable 

dspace_dependences: ['git', 'python-pip', 'python-psycopg2', 'maven', 'ant', 'openjdk-8-jdk']

# Postgress variables 

# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
#--------------------------
postgresql_hba_entries:
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
 # - {type: local, database: all, user: dspace, auth_method: md5 }

postgres_packages: ['postgresql', 'postgresql-contrib']
postgres_usr: postgres
dspace_db_name: dspace
dspace_db_user: dspace
dspace_db_pass: dspace
postgresql_daemon: postgresql
encoding: UNICODE # defaults to 'UTF-8'
postgresql_restarted_state: "restarted"
#-----------------end ---------------------------


# Tomcat Variables
tomcat_user:  tomcat
tomcat_group: tomcat
tomcat_temp_download_path: /opt
tomcat_archive_name: "apache-tomcat-8.5.32"
tomcat_archive_name_ext: ".tar.gz"
tomcat_archive_url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin"
tomcat_home_path: "/opt/tomcat"
tomcat_install_path: /opt
tomcat_archive_install_path: "{{tomcat_home_path}}/{{tomcat_archive_name}}"
tomcat_install_link: "{{tomcat_home_path}}/current"
tomcat_roles:
  - manager-gui
  - manager-script
  - manager-jmx
  - manager-status
tomcat_users: []


# dspace directories
#dspace_install_tomcat_dir:
#dspace_install_dir: "/opt"
dspace_install: "/opt/tomcat"
base_dir: "/dspace"
dspace_base_dir: /dspace/dspace_build 
dspace_source: /dspace/dspace_build/dspace-6.3-src-release
dspace_install_dir: /dspace
apache_server_hostname: repository.example.org
dspace_download_server: https://github.com/DSpace/DSpace/releases/download/dspace-6.3/dspace-6.3-src-release.tar.gz
directories_dir:
  - /dspace
    /dspace/dspace_build


# Dspace variables
dspace_user: dspace
dspace_pass: dspace
  #d2a147310ed200c73a5978baebf60e19
  #dspace

admin_email: dspace@example.com
admin_firstname: dspace
admin_lastname: dspace
admin_language: "english"
admin_password :  dspace

# theme settings
use_alt_theme: true
theme_name: "Mirage 2"
theme_path: "Mirage"
full_theme_path: "{{ dspace_install }}/webapps/xmlui/themes/{{ theme_path }}"

# vars for branding
# -----------------
logo_blue:    "002D72" #  PMS 288C
medium_blue:  "005EB8" # PMS 300C
blue_grey:    "A7BCD6" #  PMS 651C
logo:         "logo.svg"


#apache variables

apache_pkg: ['apache2', 'openssl']

# SSL vars
self_sign_cert:             true
ssl_certificate_file:       "{{ domain | replace('.', '_') }}.crt" # "star_library_jhu_edu.crt"
ssl_certificate_key_file:   "{{ domain | replace('.', '_') }}.key" # "star_library_jhu_edu.key"
ssl_certificate_chain_file: false                # "star_library_jhu_edu_interm.crt"
ssl_certificate_path:       "/etc/ssl/certs"
ssl_certificate_key_path:   "/etc/ssl/private"
ssl_certificate_subj:       "/C=US/ST=Maryland/L=Baltimore/O=JHU/CN={{ domain }}"

domain:  dspace.com
app_hostname: dspace
dspace_ip:  "10.100.7.11"


# theme settings
use_alt_theme: true
theme_name: "Mirage 2"
theme_path: "Mirage2"
full_theme_path: "{{ dspace_install }}/webapps/xmlui/themes/{{ theme_path }}"

# vars for prereqs:
# -----------------
base_install_dir: "/usr/local"
sass_version: "3.3.14"
compass_version: "1.0.1"