---

# Restart postgres
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5
# Restart tomcat 
- name: restart tomcat
  service: name=tomcat state=restarted